'use strict';
// First paint uses the same computed palette as live themes, without waiting
// for storage or JavaScript. No separately maintained fallback token tables.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..');
const context=vm.createContext({matchMedia:()=>({matches:false})});
for(const name of ['shared/settings.js','shared/theme.js'])vm.runInContext(fs.readFileSync(path.join(root,name),'utf8'),context);
const T=context.GXT.theme,D=context.GXT.DEFAULTS;
const rule=(selector,theme)=>`${selector} {\n  ${T.tokens({...D,uiTheme:theme}).split('; ').join(';\n  ')}\n}\n`;
const output='/* Generated by tools/build_ui.cjs from shared/theme.js. */\n'+rule(':root','daylight')+'@media (prefers-color-scheme: dark) {\n'+rule(':root','graphite')+'}\n';
const file=path.join(root,'shared/ui-tokens.css');
if(process.argv.includes('--check')){
  if(!fs.existsSync(file)||fs.readFileSync(file,'utf8')!==output)throw Error('Generated UI tokens are stale; run node tools/build_ui.cjs');
}else fs.writeFileSync(file,output);
console.log(process.argv.includes('--check')?'UI first-paint tokens verified':'Built UI first-paint tokens');
