"""Build the classic-script settings entry. No network or JS dependencies."""
from pathlib import Path
import json,sys
ROOT=Path(__file__).resolve().parents[1]
catalogs={p.stem:json.loads(p.read_text('utf8')) for p in sorted((ROOT/'locales').glob('*.json')) if p.stem!='inventory'}
text='// Generated by tools/build_i18n.py. Edit locales/*.json and shared/settings-core.js.\n'
text+='globalThis.GXT = globalThis.GXT || {};\nglobalThis.GXT.catalogs = '+json.dumps(catalogs,ensure_ascii=False,separators=(',',':'))+';\n'
text+=(ROOT/'shared/i18n.js').read_text('utf8')+'\n'+(ROOT/'shared/settings-core.js').read_text('utf8')
dest=ROOT/'shared/settings.js'
if '--check' in sys.argv:
    if dest.read_text('utf8')!=text:raise SystemExit('Generated settings.js is stale; run python tools/build_i18n.py')
else:dest.write_text(text,encoding='utf8',newline='')
print('UI catalog bundle verified' if '--check' in sys.argv else 'Built UI catalog bundle')
